[package]
name = "tor_resolution_lemmas_library"
version = "0.1.0"
edition = "2021"

[dependencies]
tor_functor_definition = { path = "../C051" }
derived_homology = { path = "../C054" }
tor_zero_structure = { path = "../C055" }
tor_higher_degrees = { path = "../C056" }
functoriality_of_tor = { path = "../C057" }
type_checking_interface = { path = "../C071" }

[lib]
