//! ideal_interface
//!
//! Interface for ideals in commutative rings.

#![warn(missing_docs)]

use std::collections::BTreeSet;

/// An ideal in a commutative ring
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Ideal {
    /// Generators of the ideal
    pub generators: BTreeSet<u64>,
    /// Whether this is the zero ideal
    pub is_zero: bool,
}

impl Ideal {
    /// Create the zero ideal
    pub fn zero() -> Self {
        Self {
            generators: BTreeSet::new(),
            is_zero: true,
        }
    }

    /// Create an ideal from generators
    pub fn new(generators: Vec<u64>) -> Self {
        let mut gens_vec: Vec<u64> = generators
            .into_iter()
            .filter(|&g| g != 0)
            .collect();
        gens_vec.sort();
        gens_vec.dedup();

        // Remove redundant generators: keep g only if no other generator divides it
        let gens_filtered: Vec<u64> = gens_vec
            .iter()
            .copied()
            .filter(|&g| {
                gens_vec.iter().all(|&other| {
                    g == other || g % other != 0
                })
            })
            .collect();

        let gens: BTreeSet<u64> = gens_filtered.into_iter().collect();
        let is_zero = gens.is_empty();

        Self {
            generators: gens,
            is_zero,
        }
    }

    /// Create a principal ideal (a) generated by single element
    pub fn principal(a: u64) -> Self {
        if a == 0 {
            Self::zero()
        } else {
            Self {
                generators: vec![a].into_iter().collect(),
                is_zero: false,
            }
        }
    }

    /// Number of generators
    pub fn num_generators(&self) -> usize {
        self.generators.len()
    }

    /// Check if ideal contains an element
    pub fn contains(&self, x: u64) -> bool {
        if self.is_zero {
            return x == 0;
        }
        // Simplified: check if x is divisible by some generator (gcd-based)
        self.generators.iter().any(|&g| x % g == 0)
    }

    /// Check if this ideal contains another ideal
    pub fn contains_ideal(&self, other: &Ideal) -> bool {
        if other.is_zero {
            return true;
        }
        other.generators.iter().all(|g| self.contains(*g))
    }

    /// GCD of all generators
    pub fn gcd(&self) -> u64 {
        fn gcd(a: u64, b: u64) -> u64 {
            if b == 0 { a } else { gcd(b, a % b) }
        }

        if self.generators.is_empty() {
            return 1;
        }

        self.generators
            .iter()
            .copied()
            .reduce(|a, b| gcd(a, b))
            .unwrap_or(1)
    }

    /// Intersection of two ideals (simplified)
    pub fn intersection(&self, other: &Ideal) -> Ideal {
        if self.is_zero && other.is_zero {
            return Ideal::zero();
        }
        if self.is_zero {
            return other.clone();
        }
        if other.is_zero {
            return self.clone();
        }

        let mut new_gens = self.generators.clone();
        new_gens.extend(other.generators.iter());
        Ideal::new(new_gens.into_iter().collect())
    }

    /// Sum of two ideals (generators combined)
    pub fn sum(&self, other: &Ideal) -> Ideal {
        let mut new_gens: Vec<u64> = self.generators.iter().copied().collect();
        new_gens.extend(other.generators.iter());
        Ideal::new(new_gens)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ideal_zero() {
        let ideal = Ideal::zero();
        assert!(ideal.is_zero);
        assert_eq!(ideal.num_generators(), 0);
    }

    #[test]
    fn test_ideal_principal() {
        let ideal = Ideal::principal(5);
        assert_eq!(ideal.num_generators(), 1);
        assert!(ideal.contains(10));
        assert!(ideal.contains(15));
        assert!(!ideal.contains(7));
    }

    #[test]
    fn test_ideal_new() {
        let ideal = Ideal::new(vec![2, 3, 4]);
        assert_eq!(ideal.num_generators(), 2); // 4 is redundant (gcd with 2)
    }

    #[test]
    fn test_ideal_contains() {
        let ideal = Ideal::new(vec![2, 5]);
        assert!(ideal.contains(10));
        assert!(ideal.contains(4));
        assert!(!ideal.contains(3));
    }

    #[test]
    fn test_ideal_gcd() {
        let ideal = Ideal::new(vec![6, 9, 15]);
        assert_eq!(ideal.gcd(), 3);
    }

    #[test]
    fn test_ideal_sum() {
        let ideal1 = Ideal::principal(2);
        let ideal2 = Ideal::principal(3);
        let sum = ideal1.sum(&ideal2);
        assert!(sum.contains(6));
    }
}
