//! ideal_interface
//!
//! Interface for ideals in commutative rings.

#![warn(missing_docs)]

use std::collections::BTreeSet;

fn gcd_u64(a: u64, b: u64) -> u64 {
    if b == 0 {
        a
    } else {
        gcd_u64(b, a % b)
    }
}

/// An ideal in a commutative ring
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Ideal {
    /// Generators of the ideal
    pub generators: BTreeSet<u64>,
    /// Whether this is the zero ideal
    pub is_zero: bool,
}

impl Ideal {
    /// Create the zero ideal
    pub fn zero() -> Self {
        Self {
            generators: BTreeSet::new(),
            is_zero: true,
        }
    }

    /// Create an ideal from generators
    pub fn new(generators: Vec<u64>) -> Self {
        let mut gens_vec: Vec<u64> = generators
            .into_iter()
            .filter(|&g| g != 0)
            .collect();
        gens_vec.sort();
        gens_vec.dedup();

        // Remove redundant generators: keep g only if no other generator divides it
        let gens_filtered: Vec<u64> = gens_vec
            .iter()
            .copied()
            .filter(|&g| {
                gens_vec.iter().all(|&other| {
                    g == other || g % other != 0
                })
            })
            .collect();

        let gens: BTreeSet<u64> = gens_filtered.into_iter().collect();
        let is_zero = gens.is_empty();

        Self {
            generators: gens,
            is_zero,
        }
    }

    /// Create a principal ideal (a) generated by single element
    pub fn principal(a: u64) -> Self {
        if a == 0 {
            Self::zero()
        } else {
            Self {
                generators: vec![a].into_iter().collect(),
                is_zero: false,
            }
        }
    }

    /// Number of generators
    pub fn num_generators(&self) -> usize {
        self.generators.len()
    }

    /// Check if the ideal contains `x`. Over Z every ideal is principal,
    /// generated by the gcd of its generators, so `x ∈ I ⟺ gcd(I) | x`.
    pub fn contains(&self, x: u64) -> bool {
        if self.is_zero {
            return x == 0;
        }
        x % self.gcd() == 0
    }

    /// Do the two ideals have the same elements (same gcd)?
    pub fn same_ideal(&self, other: &Ideal) -> bool {
        self.gcd() == other.gcd()
    }

    /// Check if this ideal contains another ideal
    pub fn contains_ideal(&self, other: &Ideal) -> bool {
        if other.is_zero {
            return true;
        }
        other.generators.iter().all(|g| self.contains(*g))
    }

    /// The non-negative generator of the ideal: gcd of all generators, and
    /// 0 for the zero ideal.
    pub fn gcd(&self) -> u64 {
        self.generators.iter().copied().fold(0, gcd_u64)
    }

    /// Intersection: `(a) ∩ (b) = (lcm(a, b))`; anything meets `(0)` in
    /// `(0)`. Returns `None` if the lcm overflows `u64`.
    pub fn intersection(&self, other: &Ideal) -> Option<Ideal> {
        let (a, b) = (self.gcd(), other.gcd());
        if a == 0 || b == 0 {
            return Some(Ideal::zero());
        }
        (a / gcd_u64(a, b)).checked_mul(b).map(Ideal::principal)
    }

    /// Sum of two ideals (generators combined)
    pub fn sum(&self, other: &Ideal) -> Ideal {
        let mut new_gens: Vec<u64> = self.generators.iter().copied().collect();
        new_gens.extend(other.generators.iter());
        Ideal::new(new_gens)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ideal_zero() {
        let ideal = Ideal::zero();
        assert!(ideal.is_zero);
        assert_eq!(ideal.num_generators(), 0);
    }

    #[test]
    fn test_ideal_principal() {
        let ideal = Ideal::principal(5);
        assert_eq!(ideal.num_generators(), 1);
        assert!(ideal.contains(10));
        assert!(ideal.contains(15));
        assert!(!ideal.contains(7));
    }

    #[test]
    fn test_ideal_new() {
        let ideal = Ideal::new(vec![2, 3, 4]);
        assert_eq!(ideal.num_generators(), 2); // 4 is redundant (gcd with 2)
    }

    #[test]
    fn membership_uses_the_gcd() {
        let two = Ideal::new(vec![4, 6]);
        assert!(two.contains(2));
        assert!(two.contains(10));
        assert!(!two.contains(3));
        assert!(two.same_ideal(&Ideal::principal(2)));
        let whole_ring = Ideal::new(vec![2, 5]);
        assert!(whole_ring.contains(3));
        assert_eq!(whole_ring.gcd(), 1);
    }

    #[test]
    fn test_ideal_gcd() {
        assert_eq!(Ideal::new(vec![6, 9, 15]).gcd(), 3);
        assert_eq!(Ideal::zero().gcd(), 0);
    }

    #[test]
    fn intersection_is_lcm() {
        let i = Ideal::principal(4).intersection(&Ideal::principal(6)).unwrap();
        assert!(i.same_ideal(&Ideal::principal(12)));
        let z = Ideal::principal(5).intersection(&Ideal::zero()).unwrap();
        assert!(z.is_zero);
        assert!(Ideal::principal(u64::MAX).intersection(&Ideal::principal(u64::MAX - 1)).is_none());
        for (a, b) in [(4u64, 6u64), (3, 5), (8, 12), (7, 7)] {
            let meet = Ideal::principal(a).intersection(&Ideal::principal(b)).unwrap();
            for x in 0..200 {
                assert_eq!(
                    meet.contains(x),
                    Ideal::principal(a).contains(x) && Ideal::principal(b).contains(x),
                    "({a}) ∩ ({b}) at {x}"
                );
            }
        }
    }

    #[test]
    fn containment_of_ideals() {
        assert!(Ideal::principal(2).contains_ideal(&Ideal::principal(4)));
        assert!(!Ideal::principal(4).contains_ideal(&Ideal::principal(2)));
        assert!(Ideal::principal(3).contains_ideal(&Ideal::zero()));
        assert!(!Ideal::zero().contains_ideal(&Ideal::principal(3)));
    }

    #[test]
    fn test_ideal_sum() {
        let ideal1 = Ideal::principal(2);
        let ideal2 = Ideal::principal(3);
        let sum = ideal1.sum(&ideal2);
        assert!(sum.contains(6));
    }
}
