//! krull_dimension_definition
//!
//! Krull dimension of a ring: supremum of lengths of chains of prime ideals.
//! dim(R) = sup{len(chain) : chain of primes in Spec(R)}

#![warn(missing_docs)]

pub use spectrum_definition::Spectrum;
use spectrum_order::SpecializationPreorder;
use spectrum_chains::MaximalChains;

/// The Krull dimension of a ring
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd)]
pub struct KrullDim(pub usize);

impl KrullDim {
    /// Krull dimension of a spectrum
    /// dim(R) = max(len(chain) - 1) for all prime chains
    /// or -1 if spectrum is empty
    pub fn from_spectrum(spec: &Spectrum) -> Self {
        if spec.is_empty() {
            return Self(0);
        }

        let preorder = SpecializationPreorder::from_spectrum(spec);
        let chains = MaximalChains::find_all(spec, &preorder);

        // Krull dimension is length of longest chain minus 1
        // (since chain [P0 ⊂ P1 ⊂ ... ⊂ Pn] has n+1 elements but dim n)
        if chains.longest_length() == 0 {
            Self(0)
        } else {
            Self(chains.longest_length() - 1)
        }
    }

    /// Get numeric value
    pub fn dim(&self) -> usize {
        self.0
    }

    /// Check if ring is zero-dimensional
    pub fn is_zero_dimensional(&self) -> bool {
        self.0 == 0
    }

    /// Check if ring is one-dimensional
    pub fn is_one_dimensional(&self) -> bool {
        self.0 == 1
    }

    /// Check if ring is catenary (all maximal chains have same length)
    pub fn is_catenary(spec: &Spectrum) -> bool {
        if spec.is_empty() {
            return true;
        }

        let preorder = SpecializationPreorder::from_spectrum(spec);
        let chains = MaximalChains::find_all(spec, &preorder);

        if chains.chains().is_empty() {
            return true;
        }

        let first_len = chains.chains()[0].len();
        chains.chains().iter().all(|c| c.len() == first_len)
    }

    /// Get all maximal chains achieving this dimension
    pub fn maximal_chains(spec: &Spectrum) -> Vec<Vec<u64>> {
        if spec.is_empty() {
            return vec![];
        }

        let preorder = SpecializationPreorder::from_spectrum(spec);
        let chains = MaximalChains::find_all(spec, &preorder);
        let longest_len = chains.longest_length();

        chains
            .chains()
            .iter()
            .filter(|c| c.len() == longest_len)
            .map(|c| c.elements().to_vec())
            .collect()
    }

    /// Get height upper bound from number of generators
    /// For a ring generated by n elements, dim ≤ n
    pub fn height_bound_from_generators(num_generators: usize) -> Self {
        Self(num_generators)
    }

    /// Check if dimension is achievable by localization
    /// In a catenary ring, after localization, dimension can only decrease
    pub fn localization_respects_dimension(dim_before: KrullDim, dim_after: KrullDim) -> bool {
        dim_after <= dim_before
    }
}

impl std::fmt::Display for KrullDim {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "dim = {}", self.0)
    }
}

/// Dimension computation strategy
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DimensionStrategy {
    /// Exact: enumerate prime chains
    ChainEnumeration,
    /// Upper bound: the number of points of the spectrum
    GeneratorBound,
    /// Upper bound: a chain has at most |Spec| points, so dim ≤ |Spec| − 1
    SaturationBound,
}

/// Dimension calculator with strategy
#[derive(Clone, Debug)]
pub struct DimensionCalculator {
    strategy: DimensionStrategy,
}

impl DimensionCalculator {
    /// Create calculator with given strategy
    pub fn new(strategy: DimensionStrategy) -> Self {
        Self { strategy }
    }

    /// Compute dimension based on strategy
    pub fn compute(&self, spec: &Spectrum) -> KrullDim {
        match self.strategy {
            DimensionStrategy::ChainEnumeration => KrullDim::from_spectrum(spec),
            DimensionStrategy::GeneratorBound => KrullDim(spec.len()),
            DimensionStrategy::SaturationBound => KrullDim(spec.len().saturating_sub(1)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_krull_dim_empty_spectrum() {
        let spec = Spectrum::empty();
        let dim = KrullDim::from_spectrum(&spec);
        assert_eq!(dim.dim(), 0);
    }

    #[test]
    fn test_krull_dim_single_point() {
        let spec = Spectrum::new(vec![2]);
        let dim = KrullDim::from_spectrum(&spec);
        assert_eq!(dim.dim(), 0);
        assert!(dim.is_zero_dimensional());
    }

    #[test]
    fn test_krull_dim_two_points() {
        let spec = Spectrum::new(vec![2, 3]);
        assert_eq!(KrullDim::from_spectrum(&spec), KrullDim(0));
    }

    #[test]
    fn spec_z_has_dimension_one() {
        let spec = Spectrum::new(vec![0, 2, 3, 5, 7]);
        let dim = KrullDim::from_spectrum(&spec);
        assert!(dim.is_one_dimensional());
        let chains = KrullDim::maximal_chains(&spec);
        assert_eq!(chains.len(), 4);
        assert!(chains.iter().all(|c| c.len() == 2 && c[0] == 0));
        assert!(KrullDim::is_catenary(&spec));
    }

    #[test]
    fn strategies_bound_the_exact_dimension() {
        for primes in [vec![], vec![2], vec![0, 2], vec![0, 2, 3, 5, 7, 11]] {
            let spec = Spectrum::new(primes);
            let exact = DimensionCalculator::new(DimensionStrategy::ChainEnumeration).compute(&spec);
            for s in [DimensionStrategy::GeneratorBound, DimensionStrategy::SaturationBound] {
                assert!(DimensionCalculator::new(s).compute(&spec) >= exact);
            }
        }
    }

    #[test]
    fn test_krull_dim_display() {
        let dim = KrullDim(2);
        assert_eq!(dim.to_string(), "dim = 2");
    }

    #[test]
    fn test_catenary() {
        assert!(KrullDim::is_catenary(&Spectrum::new(vec![2, 3, 5])));
        assert!(KrullDim::is_catenary(&Spectrum::empty()));
    }

    #[test]
    fn test_dimension_calculator() {
        let spec = Spectrum::new(vec![2, 3, 5]);
        let calc = DimensionCalculator::new(DimensionStrategy::ChainEnumeration);
        assert_eq!(calc.compute(&spec), KrullDim(0));
    }

    #[test]
    fn test_localization_respects_dimension() {
        let dim_before = KrullDim(3);
        let dim_after = KrullDim(2);
        assert!(KrullDim::localization_respects_dimension(dim_before, dim_after));
        assert!(!KrullDim::localization_respects_dimension(dim_after, dim_before));
    }
}
