/*
 * Sovereign IDE — Terminal Fallback Gate
 *
 * Phase 2: Terminal remains under strict user command and control.
 *
 * Three modes:
 *   DIRECT   — user keystrokes execute immediately (agent still gated)
 *   FALLBACK — all agent commands require manual Enter confirmation
 *   PREVIEW  — read-only, no execution permitted (copy only)
 *
 * Security invariant: agent-originated commands NEVER auto-execute.
 */

#ifndef SOVEREIGN_FALLBACK_GATE_H
#define SOVEREIGN_FALLBACK_GATE_H

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>
#include "../core/errors.h"

/* Forward declaration */
typedef struct Terminal Terminal;
typedef struct TerminalGate TerminalGate;

/* ================================================================
 * TYPES
 * ================================================================ */

typedef enum {
    TERMINAL_MODE_DIRECT   = 0,  /* user direct, agent still gated */
    TERMINAL_MODE_FALLBACK = 1,  /* all agent commands require confirmation */
    TERMINAL_MODE_PREVIEW  = 2,  /* read-only, no execution */
} TerminalGateMode;

typedef enum {
    CMD_SOURCE_USER  = 0,  /* typed by user directly */
    CMD_SOURCE_AGENT = 1,  /* generated by AI agent */
    CMD_SOURCE_MACRO = 2,  /* from FCL macro/keybind */
    CMD_SOURCE_HOOK  = 3,  /* from git/build hook */
} CommandSource;

typedef enum {
    GATE_OK_EXECUTED    = 0,  /* command was executed */
    GATE_OK_STAGED      = 1,  /* command staged (awaiting confirm) */
    GATE_OK_REJECTED    = 2,  /* command was rejected by user */
    GATE_OK_POPULATED   = 3,  /* text placed in terminal (no execute) */
    GATE_ERR_INVALID    = -1, /* invalid parameters */
    GATE_ERR_PENDING_FULL = -2, /* already have a pending command */
    GATE_ERR_NO_PENDING = -3, /* no pending command to confirm/reject */
    GATE_ERR_TOO_LARGE  = -4, /* command exceeds buffer */
    GATE_ERR_PREVIEW_MODE = -5, /* can't execute in preview mode */
} GateResult;

/* History entry */
typedef struct {
    char          command[4096];
    size_t        command_len;
    CommandSource source;
    bool          confirmed;
    size_t        index;
} GateHistoryEntry;

/* Statistics */
typedef struct {
    size_t           total_staged;
    size_t           total_confirmed;
    size_t           total_rejected;
    size_t           total_bypassed;
    TerminalGateMode mode;
    bool             has_pending;
} GateStats;

/* Render callback: called when staged command changes */
typedef void (*GateRenderCallback)(void *ctx, const char *command, size_t len, CommandSource source);

/* ================================================================
 * API
 * ================================================================ */

/* Lifecycle */
TerminalGate *gate_create(Terminal *terminal, TerminalGateMode mode);
void          gate_destroy(TerminalGate *g);

/* Mode control */
void             gate_set_mode(TerminalGate *g, TerminalGateMode mode);
TerminalGateMode gate_get_mode(const TerminalGate *g);

/* Command staging (called by bridge when agent produces output) */
GateResult gate_stage_command(TerminalGate *g, const char *command, size_t len, CommandSource source);

/* User actions */
GateResult gate_confirm(TerminalGate *g);                                    /* Enter = execute staged */
GateResult gate_reject(TerminalGate *g);                                     /* Escape = cancel staged */
GateResult gate_edit_pending(TerminalGate *g, const char *new_cmd, size_t len); /* Edit before confirm */

/* Populate-only (Ctrl+K D): write to terminal input, no execute */
GateResult gate_populate_only(TerminalGate *g, const char *text, size_t len);

/* User direct keystrokes (always bypass gate) */
GateResult gate_user_keystroke(TerminalGate *g, const char *data, size_t len);

/* Query */
bool             gate_has_pending(const TerminalGate *g);
const char      *gate_get_pending(const TerminalGate *g, size_t *out_len);
CommandSource    gate_get_pending_source(const TerminalGate *g);

/* History */
size_t                  gate_get_history_count(const TerminalGate *g);
const GateHistoryEntry *gate_get_history_entry(const TerminalGate *g, size_t index);

/* Render callback */
void gate_set_render_callback(TerminalGate *g, GateRenderCallback cb, void *ctx);

/* Statistics */
void gate_get_stats(const TerminalGate *g, GateStats *out);

#endif /* SOVEREIGN_FALLBACK_GATE_H */
