//! tensor_product_module
//!
//! Tensor products `M ⊗_Z N` of finitely generated abelian groups.
//!
//! `M ⊗ N` is generated by `m_i ⊗ n_j` subject to relations. For
//! presentations `M = Z^m / im A` and `N = Z^n / im B`, the relations are
//! `A_c ⊗ n_j` for every relation column `A_c` of `M` and generator `n_j`, and
//! `m_i ⊗ B_c` for every generator `m_i` and relation column `B_c` of `N`.
//! [`TensorProductModule::quotient_structure`] computes the resulting group
//! exactly with Smith normal form.

#![warn(missing_docs)]

pub use chain_complex_shape::integer_matrix;
use chain_complex_shape::integer_matrix::{check_shape, smith_form, MatrixError};
use std::collections::HashMap;

/// A generator in a tensor product, represented as a formal pair (i, j)
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct TensorGenerator {
    /// Index from first module M
    pub m_index: usize,
    /// Index from second module N
    pub n_index: usize,
}

impl TensorGenerator {
    /// Create a generator m_i ⊗ n_j
    pub fn new(m_index: usize, n_index: usize) -> Self {
        Self { m_index, n_index }
    }
}

/// A module element in the tensor product as a formal sum of generators
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TensorElement {
    /// Coefficients indexed by generator pairs
    pub coeffs: HashMap<TensorGenerator, i32>,
}

impl TensorElement {
    /// Create the zero element
    pub fn zero() -> Self {
        Self {
            coeffs: HashMap::new(),
        }
    }

    /// Create a single generator with coefficient c
    pub fn from_generator(gen: TensorGenerator, coeff: i32) -> Self {
        let mut coeffs = HashMap::new();
        if coeff != 0 {
            coeffs.insert(gen, coeff);
        }
        Self { coeffs }
    }

    /// Add another element to this one
    pub fn add(&mut self, other: &TensorElement) {
        for (gen, coeff) in &other.coeffs {
            *self.coeffs.entry(*gen).or_insert(0) += coeff;
            if self.coeffs[gen] == 0 {
                self.coeffs.remove(gen);
            }
        }
    }

    /// Scale by a coefficient
    pub fn scale(&mut self, factor: i32) {
        for coeff in self.coeffs.values_mut() {
            *coeff *= factor;
        }
        self.coeffs.retain(|_, &mut c| c != 0);
    }

    /// Is this element zero?
    pub fn is_zero(&self) -> bool {
        self.coeffs.is_empty()
    }

    /// Number of generators in the sum (with non-zero coefficient)
    pub fn num_generators(&self) -> usize {
        self.coeffs.len()
    }
}

/// A tensor product module M ⊗_Z N given by generators and relations.
#[derive(Clone, Debug)]
pub struct TensorProductModule {
    /// Number of generators of M
    pub m_rank: usize,
    /// Number of generators of N
    pub n_rank: usize,
    /// Relations among the generators `m_i ⊗ n_j`
    pub relations: Vec<TensorElement>,
}

fn to_i32(x: i64) -> Result<i32, MatrixError> {
    i32::try_from(x).map_err(|_| MatrixError::Overflow)
}

impl TensorProductModule {
    /// `Z^m ⊗ Z^n` (no relations).
    pub fn new(m_rank: usize, n_rank: usize) -> Self {
        Self {
            m_rank,
            n_rank,
            relations: Vec::new(),
        }
    }

    /// `M ⊗ N` for `M = Z^m_rank / im(m_relations)` and
    /// `N = Z^n_rank / im(n_relations)`. Relation matrices have one row per
    /// generator and one column per relation.
    pub fn from_presentations(
        m_rank: usize,
        m_relations: &[Vec<i64>],
        m_relation_count: usize,
        n_rank: usize,
        n_relations: &[Vec<i64>],
        n_relation_count: usize,
    ) -> Result<Self, MatrixError> {
        for (rel, rows, cols) in [
            (m_relations, m_rank, m_relation_count),
            (n_relations, n_rank, n_relation_count),
        ] {
            check_shape(rel, cols)?;
            if rel.len() != rows {
                return Err(MatrixError::LengthMismatch {
                    expected: rows,
                    got: rel.len(),
                });
            }
        }
        let mut module = Self::new(m_rank, n_rank);
        for c in 0..m_relation_count {
            for j in 0..n_rank {
                let mut rel = TensorElement::zero();
                for (i, row) in m_relations.iter().enumerate() {
                    rel.add(&TensorElement::from_generator(TensorGenerator::new(i, j), to_i32(row[c])?));
                }
                module.add_relation(rel);
            }
        }
        for c in 0..n_relation_count {
            for i in 0..m_rank {
                let mut rel = TensorElement::zero();
                for (j, row) in n_relations.iter().enumerate() {
                    rel.add(&TensorElement::from_generator(TensorGenerator::new(i, j), to_i32(row[c])?));
                }
                module.add_relation(rel);
            }
        }
        Ok(module)
    }

    /// Add a relation (zero relations are dropped).
    pub fn add_relation(&mut self, rel: TensorElement) {
        if !rel.is_zero() {
            self.relations.push(rel);
        }
    }

    /// Rank of the free module on the generators `m_i ⊗ n_j`, before
    /// relations. See [`Self::quotient_structure`] for the actual group.
    pub fn free_rank(&self) -> usize {
        self.m_rank * self.n_rank
    }

    /// Relation matrix: one row per generator (`m_i ⊗ n_j` at row
    /// `i · n_rank + j`), one column per relation.
    pub fn relation_matrix(&self) -> Vec<Vec<i64>> {
        let mut m = vec![vec![0i64; self.relations.len()]; self.free_rank()];
        for (c, rel) in self.relations.iter().enumerate() {
            for (gen, &coeff) in &rel.coeffs {
                if gen.m_index < self.m_rank && gen.n_index < self.n_rank {
                    m[gen.m_index * self.n_rank + gen.n_index][c] += coeff as i64;
                }
            }
        }
        m
    }

    /// The group `M ⊗ N` as `(free_rank, torsion)`: generators modulo
    /// relations, via Smith normal form.
    pub fn quotient_structure(&self) -> Result<(usize, Vec<u64>), MatrixError> {
        let snf = smith_form(&self.relation_matrix(), self.relations.len())?;
        Ok((self.free_rank() - snf.rank(), snf.torsion()))
    }

    /// Generate all basis elements (generators)
    pub fn basis_generators(&self) -> Vec<TensorGenerator> {
        let mut gens = Vec::new();
        for i in 0..self.m_rank {
            for j in 0..self.n_rank {
                gens.push(TensorGenerator::new(i, j));
            }
        }
        gens
    }

    /// Tensor element m_i ⊗ n_j
    pub fn generator(&self, i: usize, j: usize) -> Option<TensorElement> {
        if i < self.m_rank && j < self.n_rank {
            Some(TensorElement::from_generator(TensorGenerator::new(i, j), 1))
        } else {
            None
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_tensor_element_ops() {
        let g = TensorGenerator::new(0, 1);
        let mut e = TensorElement::from_generator(g, 3);
        e.add(&TensorElement::from_generator(g, -3));
        assert!(e.is_zero());
        let mut f = TensorElement::from_generator(g, 2);
        f.scale(0);
        assert!(f.is_zero());
    }

    #[test]
    fn free_modules_tensor_to_free() {
        let module = TensorProductModule::new(2, 3);
        assert_eq!(module.free_rank(), 6);
        assert_eq!(module.basis_generators().len(), 6);
        assert_eq!(module.quotient_structure(), Ok((6, vec![])));
        assert!(module.generator(1, 2).is_some());
        assert!(module.generator(2, 0).is_none());
    }

    #[test]
    fn cyclic_groups_tensor_to_gcd() {
        let z4_z6 = TensorProductModule::from_presentations(1, &[vec![4]], 1, 1, &[vec![6]], 1).unwrap();
        assert_eq!(z4_z6.quotient_structure(), Ok((0, vec![2])));
        let z2_z3 = TensorProductModule::from_presentations(1, &[vec![2]], 1, 1, &[vec![3]], 1).unwrap();
        assert_eq!(z2_z3.quotient_structure(), Ok((0, vec![])));
        let z_z5 = TensorProductModule::from_presentations(1, &[vec![]], 0, 1, &[vec![5]], 1).unwrap();
        assert_eq!(z_z5.quotient_structure(), Ok((0, vec![5])));
    }

    #[test]
    fn mixed_presentation() {
        // M = Z ⊕ Z/2 (generators m0, m1; relation 2·m1), N = Z/4.
        // M ⊗ N = Z/4 ⊕ Z/2.
        let m = TensorProductModule::from_presentations(2, &[vec![0], vec![2]], 1, 1, &[vec![4]], 1).unwrap();
        assert_eq!(m.quotient_structure(), Ok((0, vec![2, 4])));
    }

    #[test]
    fn bad_presentations_are_rejected() {
        assert!(TensorProductModule::from_presentations(2, &[vec![1]], 1, 1, &[vec![1]], 1).is_err());
        assert!(TensorProductModule::from_presentations(1, &[vec![1, 2]], 1, 1, &[vec![1]], 1).is_err());
        assert_eq!(
            TensorProductModule::from_presentations(1, &[vec![i64::MAX]], 1, 1, &[vec![]], 0).err(),
            Some(MatrixError::Overflow)
        );
    }
}
